---
author:
  - 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
distribution_type: module
generated_by: 'Module::Install version 0.74'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Lingua-Alphabet-Phonetic-NetHack
no_index:
  directory:
    - inc
    - t
requires:
  Lingua::Alphabet::Phonetic: 0
  perl: 5.004
version: 1.05
